---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/jellyfin-config:/config\n      - /mnt/servarr/data/media:/data
    ports:
      - "8096:8096"
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/sonarr-config:/config\n      - /mnt/servarr/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/radarr-config:/config\n      - /mnt/servarr/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=13013
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/bazarr-config:/config\n      - /mnt/servarr/data/media:/media
    ports:
      - "6767:6767"
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/prowlarr-config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/qbittorrent-config:/config\n      - /mnt/servarr/data/torrents:/data/torrents
    ports:
      - "8080:8080"
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=13012
      - PGID=13000
      - TZ=UTC
    volumes:
      - /mnt/servarr/config/jellyseerr-config:/app/config
    ports:
      - "5056:5055"
    restart: unless-stopped
